Task 86296: check-mark
DFE-Digital/a2b-internal pull request #244
Opened 2022-02-04 17:36 UTC by Lisa-V-Sau

Cypress test includes:

-  document Uncheck

- document Checked

2022-02-04 18:26 UTC, CathLass reviewed
It looks like you're assuming that the box will always be checked when you start these tests? We don't have stable data so that can't be guaranteed.

2022-02-04 18:58 UTC, Lisa-V-Sau commented
Yes, that did cross my mind. We don’t have another option till we get a staging environment as such.

The test checks and unchecks the box, therefore would it help if we ask everyone to also be mindful when exploring the site? I.e., to set the status back from how they found it?

2022-02-08 12:54 UTC, CathLass commented on ApplyToBecomeInternal/ApplyToBecomeCypressTests/cypress/integration/84457_TL_school-and-trust-information-proj-dates/86296_error-handling_checkmark.js
> +            // text == "Completed" || "In Progress"
can we get rid of the commented-out line now

2022-02-08 12:55 UTC, CathLass requested changes

2022-02-08 12:55 UTC, CathLass commented on ApplyToBecomeInternal/ApplyToBecomeCypressTests/cypress/integration/84457_TL_school-and-trust-information-proj-dates/86296_error-handling_checkmark.js
> +            // text == "Completed" || "In Progress"
... and the cy.log if you don't need it any more

2022-02-08 13:41 UTC, CathLass approved these changes

2022-02-08 13:48 UTC, merged