User Story 91050: Add quick-links to application form view
DFE-Digital/a2b-internal pull request #257
Opened 2022-03-21 17:09 UTC by aishajilani

2022-03-23 09:01 UTC, CathLass requested changes

2022-03-23 09:01 UTC, CathLass commented on ApplyToBecomeInternal/ApplyToBecomeInternal.Tests/Pages/ApplicationForm/ApplicationFormIntegrationTests.cs
> +		}
I think we'd have to test that the id is attached to the section header too. I had a stab at it below, but there might be a more direct way to do it
```
			// check the link text and href
			var sectionLink = Document.QuerySelector("#Overview_link");
			sectionLink.TextContent.Should().Be("Overview");
			sectionLink.Attributes
				.Where(a => a.Name == "href")
				.First().Value
				.Should().Be("#Overview");
			// check the link is associated with the correct section header
			Document.QuerySelectorAll("h2")
				.Where(contents => contents.InnerHtml == "Overview")
				.First().Attributes.Where(a => a.Name == "id")
				.First().Value
				.Should().Be("Overview");
```

2022-03-23 12:38 UTC, aishajilani commented on ApplyToBecomeInternal/ApplyToBecomeInternal.Tests/Pages/ApplicationForm/ApplicationFormIntegrationTests.cs
> +		public async void Validate_Quicklinks_On_SchoolApplicationForm()
Changed to - Should_Contain_Contents_With_Links_To_Correct_Sections()

2022-03-23 12:39 UTC, aishajilani commented on ApplyToBecomeInternal/ApplyToBecomeInternal/Pages/ApplicationForm/Index.cshtml
> -			<p class="govuk-body-s"><a asp-page="@Links.SchoolApplicationForm.Index.Page" asp-route-id="@Model.Project.Id" target="application"  id="@("application-form-link")">Open school application form in
Added back on.

2022-03-23 14:57 UTC, CathLass approved these changes
looks good

2022-03-24 11:57 UTC, kolevk approved these changes

2022-03-25 10:53 UTC, closed without merging